"""Adding urls model

Revision ID: dc26fbdbd3c8
Revises: 
Create Date: 2024-05-23 17:15:42.863026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dc26fbdbd3c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('original_url', sa.String(length=2048), nullable=False),
                    sa.Column('short_code', sa.String(length=7), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('original_url'),
                    sa.UniqueConstraint('short_code')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    # ### end Alembic commands ###
